---
- name: Check dependencies are present in Arch distros
  pacman:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - grep
    - procps  # Dep for ssh-agent.plugin.zsh
    - tar
    - which
    - zsh
  when: ansible_os_family == 'Archlinux'

- name: Download antibody install script
  get_url:
    url: https://raw.githubusercontent.com/getantibody/installer/master/install
    dest: /tmp/antibody-install.sh

- name: Install antibody
  command: bash /tmp/antibody-install.sh
  args:
    creates: /usr/local/bin/antibody

- name: create a default .zshrc
  template:
    src: .zshrc.j2
    dest: ~/.zshrc
    force: false
  become: true
  become_user: "{{ zsh_username }}"

- name: Set zsh as default shell
  user:
    name: "{{ zsh_username }}"
    shell: /bin/zsh
  become: true
